[package]
name = "clock-maybe"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
defmt = "1.0.1"
defmt-rtt = "1.1.0"
embassy-executor = { version = "0.10.0", features = [
    "platform-cortex-m",
    "executor-thread",
    "defmt"
] }
embassy-rp = { version = "0.10.0", features = [
    "critical-section-impl",
    "defmt",
    "rp235xa",
    "time-driver"
] }
embassy-time = "0.5.1"
hd44780-driver = "0.4.0"
itoa = "1.0.18"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
